### ISSUE TITLE
Implement `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by simonemarinelli** [rh389/react-native-store-view#3]
react-native 0.49.2 generates a warning:

> Module RNStoreReview requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by robhogan** [comment]
Thanks - fixed and published in 2.0.2
