### ISSUE TITLE
App is crashing on ios 8 and 9 simulator

### ISSUE THREAD

**Issue by serjek** [rh389/react-native-store-view#5]
Xcode 9.2, debug target ios 8.1 and 9.1 sim. App crashes at startup due to ```dyld: Symbol not found: _SKStoreProductParameterAdvertisingPartnerToken```.

**Comment by olegongit** [comment]
Version 3.0.0 seems not to have this problem - introduced in 3.1.0

**Comment by robhogan** [comment]
Thanks - I haven't got the setup to reproduce this just now but I imagine it's because we ought to weakly link `StoreKit`. Could I ask whether you guys are using cocoapods or linking directly (`react-native link` or manually)?

**Comment by olegongit** [comment]
We have not used Cocoapods for this - it was linked with react-native link (or perhaps manually).

**Comment by robhogan** [comment]
Ok, thanks - you might like to try `yarn add react-native-store-view@rh389/react-native-store-view#build-ios8` which attempts to fix this with runtime checks. You shouldn't need to relink.

If that works I'll package up a release.

**Comment by robhogan** [comment]
(NB - this still won't actually run on a simulator because StoreKit doesn't work on a simulator, but it should tell you with a JS error on a debug build, not just crash out)

**Comment by robhogan** [comment]
Should be fixed by 3.1.2
