### ISSUE TITLE
"With link" adds to podfile

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [rh389/react-native-store-view#7]
Hi

When I try to install the lib "With link" and not with Cocoapods, running `react-native link` adds an entry for the lib in the podfile. Is that how it's supposed to work if I don't want to use Cocoapods?

Best regards
Jens

**Comment by robhogan** [comment]
That’s now the behaviour of `react-native link` - it will auto-detect a Podfile and use it if present (docs: https://facebook.github.io/react-native/docs/linking-libraries-ios )

If you have a Podfile but don’t want to use it I think you’ll need to link manually (by dragging the project into your `Libraries` and then adding the lib to your linked dependencies under `Build phases`)

**Comment by jenskuhrjorgensen** [comment]
Okay, thanks for the snappy answer :D
